services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  bot:
<<<<<<< Updated upstream
    # restart: always
=======
    restart: always
    extra_hosts:
      - "steamcommunity.com:2.16.174.204"
>>>>>>> Stashed changes
    container_name: bot
    build: .
    volumes:
      - .:/app
