services:
  bot:
    # restart: always
    container_name: bot
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - sis-network

networks:
  sis-network:
    external: true
